---
- hosts: all
  tasks:
    - name: "Instalar pip3"
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - python3-pymysql
        - python3-pip
    - name: "Criar BD mySQL"
      community.mysql.mysql_db:
        name: wordpress_db
        state: present
        login_user: dba
    - name: "Criar o User Database com todos os privilegios"
      login_user: dba
      community.mysql.mysql_user:
        name: bob
        password: 12345
        priv: '*.*:ALL,GRANT'
        state: present  
