---
- hosts: all
  tasks:
    - name: "Instalar pip3"
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - python3-pymysql
        - python3-pip
        
      became: yes
      community.mysql.mysql_db:
        name: wordpress_db
        state: present
