---
- hosts: all
  tasks:
    - name: "Instalar pip3"
      apt:
        name: python3-pip
        state: latest
    - name: "Instalar pyMySql"
      pip: 
        nane: pymysql
        state: preset
    - name: "Cria o banco do MySQL" 
      community.mysql.mysql_db:
        name: wordpress_db
        state: present
        login_user: root