---
- hosts: all
  tasks:
    - name: "Cria o banco do MySQL"  # Corrected indentation and quotes
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
      become: yes
      ansible_python_interpreter: /usr/bin/python3
