---
- hosts: all
  tasks:
    - name: "Instalar pip3"
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - python3-pymysql
        - python3-pip
    - name: "Criar BD mySQL"
      community.mysql.mysql_db:
        name: wordpress_db
        state: present
        login_user: dba
    - name: "Criar o User Database com todos os privilegios"      
      community.mysql.mysql_user:
        login_user: dba
        name: wordpress_user
        password: 12345
        priv: 'wordpress_db.*:ALL'
        state: present  
