---
- hosts: all
  tasks:
    - name: "Instalar pip3"
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - python3-pymysql
        - python3-pip
    - name: "Cria o banco do MySQL" 
      community.mysql.mysql_db:
        name: wordpress_db
        state: present
        login_user: root