- hosts: all
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php8.2
        - apache2
        - libapache2-mod-php8.2
        - php8.2-gd
        - php8.2-mcrypt
        - default-mysql-server
        - php8.2-mysql
