---
- hosts: all
  tasks:
    - name: 'Instala o PHP'
      apt:
        name: php8.2
        state: latest
      become: yes
    - name: 'Instala o Apache2'
      apt: 
        name: apache2
        state: latest
      become: yes
    - name: 'Instala o ModPHP'
      apt: 
        name: libapache2-mod-php8.2
        state: latest
      become: yes